version: '3'

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: smgames
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: need_to_make_this_secure
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
